### ISSUE TITLE
Can't download apk

### ISSUE THREAD

**Issue by Dinofyfy** [K3V1991/ADB-and-FastbootPlusPlus#6]
I manually downloaded it and powershell gives me this problem after installing a apk on my android:
![Screenshot 2024-05-20 170026](https://github.com/K3V1991/ADB-and-FastbootPlusPlus/assets/149675248/7298fc81-3f46-4a72-988e-66c7ba95712a)
On my Android it just says that the apk is unsafe to install.

**Comment by Dinofyfy** [comment]
Got it to work because its a shitty xiamoi problem thanks for this cool shit

**Comment by tahayparker** [comment]
mind closing the issue if it's resolved? thanks
